spring:
  application:
    name: ms-categoria
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Mueve flyway aquí dentro:
  flyway:
    enabled: true
    locations: classpath:db/migration
    # Esto es lo que Spring Boot usa internamente para validar
    check-location: false
    ignore-missing-migrations: true

server:
  port: ${PORT:8081}

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

ms:
  juegos:
    url: ${JUEGOS_SERVICE_URL:http://localhost:8082}